### ISSUE TITLE
missing changes for  v1.17.0?

### ISSUE THREAD

**Issue by creamsoup** [googleapis/common-protos-java#13]
current master branch doesn't have any commits for `v1.17.0` (latest change is made 6 months ago),
but maven central has newer release [`v1.17.0`](https://mvnrepository.com/artifact/com.google.api.grpc/proto-google-common-protos/1.17.0).

where does it come from? can we use/trust v1.17.0?

is there any release notes? also, having tags for each release would be nice.

**Comment by yihanzhen** [comment]
Hi, @vam-google released v1.17.0 from [api-client-staging](https://github.com/googleapis/api-client-staging) repo. The artifact can be trusted.

**Comment by creamsoup** [comment]
okay thanks, @hzyi-google. The published pom indicates the api-client-staging repo in scm section, so it's my bad to create an issue here. but this raises a question, what is the purpose of this repo?

**Comment by yihanzhen** [comment]
This repo is very much abandoned. [googleapis/googleapis](https://github.com/googleapis/googleapis) is the source of truth for all public-facing protos.

(I'll check with the team, we should probably archive this repo if indeed no one else is depending on it)

**Comment by chingor13** [comment]
Apologies for this - we were releasing this artifact from multiple repositories, but from now on, all releases of this artifact will come from https://github.com/googleapis/java-common-protos.

For the source from previous versions, those are published (and signed) as part of releases to Maven Central.
