### ISSUE TITLE
Enable master branch protection

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/common-protos-java#16]
This repository does not seem to have master branch
          protection enabled, at least in the way I'm expecting.
          I was hoping for:

          - master branch protection
          - requiring at least one code reviewer
          - requiring at least two status checks
          - enforcing rules for admins

          Please turn it on!

**Comment by SurferJeffAtGoogle** [comment]
Andrea, d you still maintain this repo?

**Comment by chingor13** [comment]
This repo will be archived. See https://github.com/googleapis/java-common-protos for all future development.
